# Generated by Django 3.2.4 on 2021-06-19 13:47

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('pizzaType', models.CharField(choices=[('regular', 'Regular'), ('square', 'Square')], max_length=50)),
                ('pizzaSize', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=50)),
                ('pizzaTopping', models.CharField(max_length=100)),
            ],
        ),
    ]
