# Generated by Django 3.2.4 on 2021-06-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename__id_pizza_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='id',
            new_name='_id',
        ),
    ]
